### ISSUE TITLE
Intent is sometimes null on onStartCommand in spite of START_STICKY_COMPATIBILITY returns

### ISSUE THREAD

**Issue by kokufu** [kokufu/FuseDroid#2]
User crash reports.

App version: 0.3
Android version: 4.1, 5.0, 5.1

```
java.lang.RuntimeException: Unable to start service com.kokufu.android.apps.fusedroid.MainService@422297b8 with null: java.lang.NullPointerException
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2582)
    at android.app.ActivityThread.access$2000(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1334)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:174)
    at android.app.ActivityThread.main(ActivityThread.java:4952)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.kokufu.android.apps.fusedroid.MainService.onStartCommand(MainService.java:61)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2565)
    ... 10 more
```

**Comment by kokufu** [comment]
START_STICKY_COMPATIBILITY may not work on newer version of Android.
I decided to use START_REDELIVER_INTENT instead.
